### ISSUE TITLE
Following up from your upgrade to boardgame.io

### ISSUE THREAD

**Issue by delucis** [Oliboy50/coinche#12]
Hey @Oliboy50, glad you got your upgrade to the latest boardgame.io working.

In case it’s helpful, this is my understanding of your game flow based on your code using `0.32.1`:

![State Diagram](https://mermaid.ink/img/eyJjb2RlIjoic3RhdGVEaWFncmFtXG4gICAgWypdIC0tPiBUYWxrXG4gICAgXG4gICAgc3RhdGUgVGFsayB7XG4gICAgICAgIFsqXSAtLT4gdHVybjogVGFsay5vbkJlZ2luXFxuKERlYWwpXG4gICAgICAgIHN0YXRlIHR1cm4ge1xuICAgICAgICAgICAgc3RhdGUgY2hvb3NlIDw8Zm9yaz4-XG4gICAgICAgICAgICAgICAgWypdIC0tPiBjaG9vc2VcbiAgICAgICAgICAgIHN0YXRlIGVuZCA8PGpvaW4-PlxuICAgICAgICAgICAgICAgIGNob29zZSAtLT4gZW5kOiBzYXlTa2lwXG4gICAgICAgICAgICAgICAgY2hvb3NlIC0tPiBlbmQ6IHNheVRha2VcbiAgICAgICAgICAgICAgICBlbmQgLS0-IFsqXTogdHVybi5vbkVuZFxuICAgICAgICB9XG4gICAgICAgIHN0YXRlIHNob3VsZEVuZCA8PGZvcms-PlxuICAgICAgICAgICAgdHVybiAtLT4gc2hvdWxkRW5kOiBUYWxrLmVuZElmXG4gICAgICAgICAgICBzaG91bGRFbmQgLS0-IHR1cm5cbiAgICAgICAgICAgIHNob3VsZEVuZCAtLT4gWypdOiBUYWxrLm9uRW5kXG4gICAgfVxuXG4gICAgbm90ZSBsZWZ0IG9mIFRhbGtcbiAgICAgICAgbmV4dCA9IFBsYXlDYXJkcyxcbiAgICAgICAgc3RhcnQgPSB0cnVlXG4gICAgZW5kIG5vdGVcbiAgICBcbiAgICBUYWxrIC0tPiBQbGF5Q2FyZHNcblxuICAgIHN0YXRlIFBsYXlDYXJkcyB7XG4gICAgICAgIFsqXSAtLT4gdHVyblxuICAgICAgICBzdGF0ZSB0dXJuIHtcbiAgICAgICAgICAgIFsqXSAtLT4gWypdOiBwbGF5Q2FyZFxuICAgICAgICB9XG4gICAgICAgIHN0YXRlIGVuZFR1cm4gPDxmb3JrPj5cbiAgICAgICAgdHVybiAtLT4gZW5kVHVybjogUGxheUNhcmRzLmVuZElmXG4gICAgICAgIGVuZFR1cm4gLS0-IHR1cm5cbiAgICAgICAgZW5kVHVybiAtLT4gWypdOiBQbGF5Q2FyZHMub25FbmRcXG4oQ291bnRQb2ludHMpXG5cbiAgICB9XG5cbiAgICBub3RlIHJpZ2h0IG9mIFBsYXlDYXJkc1xuICAgICAgICAgIG5leHQgPSBUYWxrXG4gICAgZW5kIG5vdGVcblxuICAgIHN0YXRlIGVuZFBsYXlDYXJkcyA8PGZvcms-PlxuICAgICAgICBQbGF5Q2FyZHMgLS0-IGVuZFBsYXlDYXJkczogR2FtZS5lbmRJZlxuICAgICAgICBlbmRQbGF5Q2FyZHMgLS0-IFRhbGtcbiAgICAgICAgZW5kUGxheUNhcmRzIC0tPiBbKl0iLCJtZXJtYWlkIjp7InRoZW1lIjoiZm9yZXN0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

There are two phases if we understand phases as states where players make phase-specific moves. Each of them actually only has one `next` phase: Talk → PlayCards and PlayCards → Talk.

Instead of ending `Talk` and returning to `Talk` (via `Deal`), you would check in `turn.onEnd` if you need to deal or reset state inside `Talk`. And similarly with `PlayCards` you only end the phase once playing cards has ended and the game will either be over (tested by `Game.endIf`) or pass back to the `Talk` phase. Does this make sense?

Sorry you had all that trouble with the phase events!

**Comment by Oliboy50** [comment]
👋 Thank you again for your time 🙇 

It does make sense, indeed. 
And it would probably also work using only 2 phases 👍

The fact is that: 
- conceptually, it makes more sense to me to have the `Deal`/`CountPoint` extra phases (because "in real life", these phases "exist")
- if I had used only 2 phases, I would have feared the possibility that a user could still call a `move` during the computing stuff (dealing/counting)... and I want to avoid bugs as much as possible
- the "dealer" (player which deals the cards) is not the same than the player which starts "talking"  (so I though I'd have to build different turn logic for this 2 phases)

Anyway, my new current solution isn't perfect... but it perfectly works and this is all I want ATM 😃 

Thanks for your support

**Comment by delucis** [comment]
You're welcome. I agree that your approach was reasonable conceptually. Hopefully a solution that allows that to work will exist in the future, but in general the aim is for phases to manage turns etc rather than just for changing state.

As for your second concern: while the framework is running its hooks and calculations, in any case other actions will be ignored, so different phases aren't any more safe.

Enjoy your game!
